from enum import Enum
from os import getenv, path
from dotenv import load_dotenv

load_dotenv(dotenv_path=path.join(path.dirname(path.dirname(path.dirname(__file__))), ".env"))
DOWNLOAD_PATH = getenv("DOWNLOAD_PATH") or "downloads"

class VideoTargetKeys(str, Enum):
  ID = "id"
  FULLTITLE = "fulltitle"
  TITLE = "title"
  THUMBNAILS = "thumbnails"
  THUMBNAIL = "thumbnail"
  CHANNEL_ID = "channel_id"
  CHANNEL = "channel"
  CHANNEL_FOLLOWERS = "channel_follower_count"
  CHANNEL_VERIFIED = "channel_is_verified"
  DURATION = "duration"
  DURATION_STRING = "duration_string"
  VIEWS = "view_count"
  LIKES = "like_count"
  URL = "webpage_url"
  ORIGINAL_URL = "original_url"
  DISPLAY_ID = "display_id"
  EXTRACTOR = "extractor"
  EXTRACTOR_KEY = "extractor_key"
  ALBUM = "album"
  ARTISTS = "artists"
  ARTIST = "artist"
  CREATOR = "creator"
  TAGS = "tags"
  TRACK = "track"
  RELEASE_DATE = "release_date"
  RELEASE_YEAR = "release_year"
  AVAILABILITY = "availability"
  REQUESTED_DOWNLOADS = "requested_downloads"
  RESOLUTION = "resolution"
  AUDIO_EXT = "audio_ext"
  VIDEO_EXT = "video_ext"
  FILESIZE = "filesize"

class PlaylistTargetKeys(str, Enum):
  ID = "id"
  TITLE = "title"
  DESCRIPTION = "description"
  THUMBNAILS = "thumbnails"
  MODIFIED_DATE = "modified_date"
  CHANNEL = "channel"
  CHANNEL_ID = "channel_id"
  CHANNEL_URL = "channel_url"
  VIEWS = "view_count"
  COUNT = "playlist_count"
  ENTRIES = "entries"
  EXTRACTOR = "extractor"
  EXTRACTOR_KEY = "extractor_key"
  WEBPAGE_URL = "webpage_url"
  ORIGINAL_URL = "original_url"

class AuthorTargetKeys(str, Enum):
  ID = "id"
  UPLOADER_ID = "uploader_id"
  CHANNEL = "channel"
  DESCRIPTION = "description"
  THUMBNAILS = "thumbnails"
  CHANNEL_URL = "channel_url"
  TAGS = "tags"
  MODIFIED_DATE = "modified_date"
  EXTRACTOR = "extractor"
  EXTRACTOR_KEY = "extractor_key"
  FOLLOWER_COUNT = "channel_follower_count"
  VIEWS = "view_count"
  ENTRIES = "entries"
  PLAYLIST_COUNT = "playlist_count"

class ThumbnailStrategy(Enum):
  FIRST = "first"
  LAST = "last"
  HIGHEST_RES = "highest_res"
  LOWEST_RES = "lowest_res"
